---
title: "Singular Value Decomposition"
output: word_document
date: "2024-07-15"
---
```{r Import module}
library(readxl)
```

```{r Inisialisasi data}
data <- read_excel("C:/R Script/Singular Value Decomposition/Singular Value Decomposition.xlsx", 
    col_types = c("skip", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))
head(data)
```
```{r Jadikan matriks}
data_matrix <- as.matrix(data)
head(round(data_matrix,digits=3))
```
```{r Menerapkan svd}
svd_result <- svd(data_matrix)
u <- svd_result$u
d <- svd_result$d
v <- svd_result$v
svd_result
```

```{r Matriks orthogonal kiri}
cat("\nMatriks orthogonal kiri\n")
head(u)
```
```{r Vektor nilai singular}
cat("\nVektor nilai singular\n")
d
```

```{r Matriks orthogonal kanan}
cat("\nMatriks orthogonal kanan\n")
head(v)
```
```{r Mengonstruksi ulang matriks asli}
reconstructed_matrix <- u %*% diag(d) %*% t(v)
head(reconstructed_matrix)
```

```{r Melihat dimensi data}
dim(data)
dim(reconstructed_matrix)
```

